# Random Sampling

In [1]:
import numpy as np

In [2]:
np.random.rand(2,4)

array([[0.81056764, 0.26076145, 0.48325247, 0.55697493],
       [0.75459924, 0.67413036, 0.58554431, 0.5103371 ]])

In [5]:
np.random.randn(2,4)

array([[-0.5011372 , -0.33828647, -0.63645032,  0.08687543],
       [ 0.20224788, -1.22922616, -0.19874565,  0.4216612 ]])

In [6]:
np.random.randint(1,100, (2,4) )

array([[99, 51, 42, 63],
       [27, 46, 54,  8]])

In [7]:
xs = np.random.randint(100, size=10)
ys =  np.random.randint(100, size=10)
points = zip(xs, ys)
for point in points:
    print(point)

(25, 99)
(42, 13)
(21, 65)
(61, 48)
(2, 53)
(18, 9)
(61, 99)
(54, 38)
(64, 98)
(4, 20)


### It's Fast!

In [8]:
import random 

In [9]:
%%timeit -n 1000
ar = np.random.randint(0, 100001, 1000)
np.mean(ar)

18.3 µs ± 3.39 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%%timeit -n 1000
ls = random.sample(range(100000), 1000)
sum(ls)/len(ls)

670 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
