# Random Sampling

In [2]:
import numpy as np

In [3]:
np.random.rand(2,4)

array([[0.52574419, 0.57669131, 0.36813113, 0.484198  ],
       [0.42378184, 0.78825959, 0.06231872, 0.58643782]])

In [4]:
np.random.randn(2,4)

array([[-1.35092824,  0.21016302,  2.4503385 ,  0.10856017],
       [-0.48446235, -0.68646211,  0.53018275, -0.48612985]])

In [5]:
np.random.randint(1,100, (2,4) )

array([[32, 16, 94, 55],
       [75,  5, 69, 41]])

In [6]:
xs = np.random.randint(100, size=10)
ys =  np.random.randint(100, size=10)
points = zip(xs, ys)
for point in points:
    print(point)

(29, 37)
(29, 84)
(78, 16)
(51, 15)
(84, 13)
(55, 7)
(90, 56)
(22, 51)
(55, 93)
(71, 43)


### It's Fast!

In [8]:
import random 

In [9]:
%%timeit -n 1000
ar = np.random.randint(0, 100001, 1000)
np.mean(ar)

18.5 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%%timeit -n 1000
ls = random.sample(range(100000), 1000)
sum(ls)/len(ls)

745 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
