# Random Sampling

In [1]:
import numpy as np

In [2]:
np.random.rand(2,4)

array([[0.10746948, 0.62823816, 0.02114681, 0.88716548],
       [0.68765508, 0.35473535, 0.75012164, 0.60343113]])

In [3]:
np.random.randn(2,4)

array([[ 0.31975743, -0.82213441, -0.07933496,  0.98061568],
       [ 0.44393031,  0.19468999,  0.29237133,  1.94151488]])

In [4]:
np.random.randint(1,100, (2,4) )

array([[42, 75, 69, 73],
       [59, 55, 99, 54]])

In [5]:
xs = np.random.randint(100, size=10)
ys =  np.random.randint(100, size=10)
points = zip(xs, ys)
for point in points:
    print(point)

(53, 20)
(93, 59)
(41, 25)
(36, 55)
(97, 35)
(10, 90)
(39, 54)
(52, 62)
(97, 2)
(49, 46)


### It's Fast!

In [6]:
import random 

In [7]:
%%timeit -n 1000
ar = np.random.randint(0, 100001, 1000)
np.mean(ar)

22 µs ± 4.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit -n 1000
ls = random.sample(range(100000), 1000)
sum(ls)/len(ls)

740 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
