# Random Sampling

In [1]:
import numpy as np

In [2]:
np.random.rand(2,4)

array([[0.72714784, 0.13619741, 0.70820692, 0.78272684],
       [0.33557043, 0.77061924, 0.00969337, 0.20658653]])

In [3]:
np.random.randn(2,4)

array([[-0.42828287, -0.33896633, -0.34522914, -1.06683798],
       [-0.15381925, -1.55783295, -0.09436546, -0.12203901]])

In [4]:
np.random.randint(1,100, (2,4) )

array([[30, 77, 87, 56],
       [20, 49, 49, 19]])

In [5]:
xs = np.random.randint(100, size=10)
ys =  np.random.randint(100, size=10)
points = zip(xs, ys)
for point in points:
    print(point)

(33, 50)
(42, 63)
(83, 34)
(81, 19)
(82, 89)
(92, 11)
(36, 63)
(73, 39)
(36, 43)
(51, 23)


### It's Fast!

In [6]:
import random 

In [7]:
%%timeit -n 1000
ar = np.random.randint(0, 100001, 1000)
np.mean(ar)

22.9 µs ± 5.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit -n 1000
ls = random.sample(range(100000), 1000)
sum(ls)/len(ls)

718 µs ± 25.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
